### ISSUE TITLE
thank you! (fractions?)

### ISSUE THREAD

**Issue by lhayhurst** [mkutny/absorbing-markov-chains#1]
Thanks for this project! It worked perfectly for me, and by stepping through your code I felt like I got a good hands on feel for the solution. 

I have a few unit tests which I can submit in, and also a modified your code a little to support fractions as an optional in memory data type for the values. All your math and linear algebra code worked just fine when switched over to the Fraction type (yay Python). 

Would you like me to submit a PR with an optional use_fractions=False parameter?

Cheers!

**Comment by lhayhurst** [comment]
I submitted a PR!

**Comment by mkutny** [comment]
Thanks! I'm glad you've found this small utility helpful.

Just out of curiosity: what was the need to switch to Fractions? I intentionally made it with zero dependencies as some projects require a barebones implementation, you know.

**Comment by lhayhurst** [comment]
Yep! I was solving the foo.bar challenge #3.1 (see https://github.com/ivanseed/google-foobar-help/blob/master/challenges/doomsday_fuel/doomsday_fuel.md). It's output is a probability vector in the form of (numerator,numerator,....,denominator), with the last value in the vector being the common denominator that all the numerators share. 

Re: minimum dependencies, yeah, that is why I selected to use your library (the challenge doesn't allow anything but standard python libraries IIRC). Since Fraction is a built-in lib I figured it was safe :-) (it was). Regardless, totally understand if you want to keep your version dependency free and reject the PR!

**Comment by mkutny** [comment]
I didn't mention the challenge intentionally because it requires some thought to figure out it'd require absorbing Markov chains to solve. This part of the challenge is fun.

On the other hand, matrix manipulations don't require any thought at all, just time to code all the math. This part of the challenge is boring.

So with this code, I wanted to save people some time but didn't have an intention to devoid them from thinking at all.

Anyway, as it worked in your case I'm merging it.
